import { useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { CASE_HISTORY } from "@/data/mock";
import { Panel, SectionTitle, StatusBadge } from "@/components/Common/primitives";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/history")({
  head: () => ({
    meta: [
      { title: "Case History — OceanTrace Archive" },
      {
        name: "description",
        content:
          "Archive of completed and monitored oil spill investigations with slick area, region and top forensic evidence score.",
      },
      { property: "og:title", content: "Case History — OceanTrace" },
      {
        property: "og:description",
        content: "Historical marine oil spill investigations and attribution outcomes.",
      },
    ],
  }),
  component: History,
});

const FILTERS = ["ALL", "ACTIVE", "MONITORING", "RESOLVED"] as const;

function History() {
  const [filter, setFilter] = useState<(typeof FILTERS)[number]>("ALL");
  const navigate = useNavigate();
  const rows = CASE_HISTORY.filter((c) => filter === "ALL" || c.status === filter);

  return (
    <div className="space-y-5">
      <SectionTitle
        kicker="Investigations"
        title="Case History"
        description="Every investigation generated by the platform, retained for forensic audit."
        right={
          <div className="flex gap-1.5">
            {FILTERS.map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={cn(
                  "rounded-md border px-2.5 py-1 num text-[10px] tracking-widest uppercase",
                  filter === f
                    ? "border-cyan/45 bg-cyan/12 text-cyan"
                    : "border-hairline text-muted-foreground hover:text-foreground",
                )}
              >
                {f}
              </button>
            ))}
          </div>
        }
      />

      <Panel bodyClassName="p-0">
        <table className="w-full text-left text-[12.5px]">
          <thead>
            <tr className="border-b border-hairline">
              {["Case ID", "Region", "Observed", "Status", "Spill Area", "Candidates", "Top Evidence"].map(
                (h) => (
                  <th key={h} className="label-xs px-4 py-2.5 font-normal">
                    {h}
                  </th>
                ),
              )}
            </tr>
          </thead>
          <tbody>
            {rows.map((c) => (
              <tr
                key={c.id}
                onClick={() => navigate({ to: "/cases/$caseId", params: { caseId: c.id } })}
                className="cursor-pointer border-b border-hairline/50 transition-colors hover:bg-cyan/6"
              >
                <td className="num px-4 py-3 text-cyan">{c.id}</td>
                <td className="px-4 py-3">{c.region}</td>
                <td className="num px-4 py-3 text-muted-foreground">
                  {new Date(c.observedAt).toISOString().slice(0, 16).replace("T", " ")} UTC
                </td>
                <td className="px-4 py-3">
                  <StatusBadge status={c.status} />
                </td>
                <td className="num px-4 py-3 text-oil">{c.areaKm2} km²</td>
                <td className="num px-4 py-3 text-muted-foreground">{c.candidates}</td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    <div className="h-1 w-20 overflow-hidden rounded-full bg-muted">
                      <div
                        className="h-full bg-cyan"
                        style={{ width: `${c.topScore * 100}%` }}
                      />
                    </div>
                    <span className="num text-cyan">{Math.round(c.topScore * 100)}%</span>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Panel>
    </div>
  );
}
