/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AisRouteImport } from './routes/ais'
import { Route as AttributionRouteImport } from './routes/attribution'
import { Route as CharacterizationRouteImport } from './routes/characterization'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as ModelRouteImport } from './routes/model'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AisRoute = AisRouteImport.update({
  id: '/ais',
  path: '/ais',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionRoute = AttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterizationRoute = CharacterizationRouteImport.update({
  id: '/characterization',
  path: '/characterization',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/attribution': typeof AttributionRoute
  '/characterization': typeof CharacterizationRoute
  '/detection': typeof DetectionRoute
  '/drift': typeof DriftRoute
  '/environment': typeof EnvironmentRoute
  '/history': typeof HistoryRoute
  '/ingest': typeof IngestRoute
  '/model': typeof ModelRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/vessels': typeof VesselsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/attribution': typeof AttributionRoute
  '/characterization': typeof CharacterizationRoute
  '/detection': typeof DetectionRoute
  '/drift': typeof DriftRoute
  '/environment': typeof EnvironmentRoute
  '/history': typeof HistoryRoute
  '/ingest': typeof IngestRoute
  '/model': typeof ModelRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/vessels': typeof VesselsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/attribution': typeof AttributionRoute
  '/characterization': typeof CharacterizationRoute
  '/detection': typeof DetectionRoute
  '/drift': typeof DriftRoute
  '/environment': typeof EnvironmentRoute
  '/history': typeof HistoryRoute
  '/ingest': typeof IngestRoute
  '/model': typeof ModelRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/vessels': typeof VesselsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ais'
    | '/attribution'
    | '/characterization'
    | '/detection'
    | '/drift'
    | '/environment'
    | '/history'
    | '/ingest'
    | '/model'
    | '/overview'
    | '/settings'
    | '/sources'
    | '/vessels'
    | '/cases/$caseId'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ais'
    | '/attribution'
    | '/characterization'
    | '/detection'
    | '/drift'
    | '/environment'
    | '/history'
    | '/ingest'
    | '/model'
    | '/overview'
    | '/settings'
    | '/sources'
    | '/vessels'
    | '/cases/$caseId'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/ais'
    | '/attribution'
    | '/characterization'
    | '/detection'
    | '/drift'
    | '/environment'
    | '/history'
    | '/ingest'
    | '/model'
    | '/overview'
    | '/settings'
    | '/sources'
    | '/vessels'
    | '/cases/$caseId'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AisRoute: typeof AisRoute
  AttributionRoute: typeof AttributionRoute
  CharacterizationRoute: typeof CharacterizationRoute
  DetectionRoute: typeof DetectionRoute
  DriftRoute: typeof DriftRoute
  EnvironmentRoute: typeof EnvironmentRoute
  HistoryRoute: typeof HistoryRoute
  IngestRoute: typeof IngestRoute
  ModelRoute: typeof ModelRoute
  OverviewRoute: typeof OverviewRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  VesselsRoute: typeof VesselsRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ais': {
      id: '/ais'
      path: '/ais'
      fullPath: '/ais'
      preLoaderRoute: typeof AisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribution': {
      id: '/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characterization': {
      id: '/characterization'
      path: '/characterization'
      fullPath: '/characterization'
      preLoaderRoute: typeof CharacterizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AisRoute: AisRoute,
  AttributionRoute: AttributionRoute,
  CharacterizationRoute: CharacterizationRoute,
  DetectionRoute: DetectionRoute,
  DriftRoute: DriftRoute,
  EnvironmentRoute: EnvironmentRoute,
  HistoryRoute: HistoryRoute,
  IngestRoute: IngestRoute,
  ModelRoute: ModelRoute,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  VesselsRoute: VesselsRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
